app = "clean-writer-ruby-version"
primary_region = "iad"

[build]

[deploy]
  release_command = "bin/rails db:prepare"

[env]
  RAILS_LOG_LEVEL = "info"
  RAILS_SERVE_STATIC_FILES = "true"
  SOLID_QUEUE_IN_PUMA = "true"
  HTTP_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
