import { RisoTheme } from "../types";

export const THEME_STORAGE_KEY = "clean_writer_theme";
export const FONT_STORAGE_KEY = "clean_writer_font";
export const BUILD_NUMBER = `v${"0.1.0"}`;
export const BUILD_TRACK = "nerv";
export const BUILD_HASH = "dev";
export const BUILD_IDENTITY = `${BUILD_NUMBER} · ${BUILD_TRACK} · ${BUILD_HASH}`;

export const FONT_CATEGORIES = ["Mono", "Sans-serif", "Serif", "Handwriting"] as const;
export type FontCategory = (typeof FONT_CATEGORIES)[number];

export const FONT_OPTIONS = [
  // Mono
  {
    id: "courier-prime",
    name: "Courier Prime",
    family: '"Courier Prime", monospace',
    category: "Mono" as FontCategory,
  },
  {
    id: "space-mono",
    name: "Space Mono",
    family: '"Space Mono", monospace',
    category: "Mono" as FontCategory,
  },
  {
    id: "jetbrains",
    name: "JetBrains Mono",
    family: '"JetBrains Mono", monospace',
    category: "Mono" as FontCategory,
  },
  {
    id: "fira-code",
    name: "Fira Code",
    family: '"Fira Code", monospace',
    category: "Mono" as FontCategory,
  },
  {
    id: "ibm-plex-mono",
    name: "IBM Plex Mono",
    family: '"IBM Plex Mono", monospace',
    category: "Mono" as FontCategory,
  },
  // Sans-serif
  {
    id: "inter",
    name: "Inter",
    family: '"Inter", sans-serif',
    category: "Sans-serif" as FontCategory,
  },
  {
    id: "dm-sans",
    name: "DM Sans",
    family: '"DM Sans", sans-serif',
    category: "Sans-serif" as FontCategory,
  },
  {
    id: "plus-jakarta",
    name: "Plus Jakarta Sans",
    family: '"Plus Jakarta Sans", sans-serif',
    category: "Sans-serif" as FontCategory,
  },
  {
    id: "helvetica",
    name: "Helvetica",
    family: 'Helvetica, "Helvetica Neue", Arial, sans-serif',
    category: "Sans-serif" as FontCategory,
  },
  {
    id: "rubik",
    name: "Rubik",
    family: '"Rubik", sans-serif',
    category: "Sans-serif" as FontCategory,
  },
  {
    id: "system",
    name: "System",
    family: "system-ui, -apple-system, sans-serif",
    category: "Sans-serif" as FontCategory,
  },
  // Serif
  {
    id: "lora",
    name: "Lora",
    family: '"Lora", serif',
    category: "Serif" as FontCategory,
  },
  {
    id: "merriweather",
    name: "Merriweather",
    family: '"Merriweather", serif',
    category: "Serif" as FontCategory,
  },
  {
    id: "playfair",
    name: "Playfair Display",
    family: '"Playfair Display", serif',
    category: "Serif" as FontCategory,
  },
  {
    id: "eb-garamond",
    name: "EB Garamond",
    family: '"EB Garamond", serif',
    category: "Serif" as FontCategory,
  },
  // Handwriting
  {
    id: "caveat",
    name: "Caveat",
    family: '"Caveat", cursive',
    category: "Handwriting" as FontCategory,
  },
] as const;

export type FontId = (typeof FONT_OPTIONS)[number]["id"];

export const THEMES: RisoTheme[] = [
  {
    id: "classic",
    name: "Classic",
    text: "#333333",
    background: "#FDFBF7",
    highlight: {
      noun: "#0078BF",
      pronoun: "#9B59B6",
      verb: "#F15060",
      adjective: "#00A95C",
      adverb: "#E67E22",
      preposition: "#1ABC9C",
      conjunction: "#FF6C2F",
      article: "#5F6C6D", // Fixed: was #7F8C8D (2.5:1), now darker for 3.5:1+
      interjection: "#E91E63",
      url: "#2980B9",
      number: "#8E6F3E",
      hashtag: "#2980B9",
    },
    accent: "#F15060",
    cursor: "#F15060",
    strikethrough: "#F15060",
    selection: "rgba(241,80,96,0.2)",
  },
  {
    id: "blueprint",
    name: "Blueprint",
    text: "#FDFBF7",
    background: "#0078BF",
    highlight: {
      noun: "#FFE800",
      pronoun: "#E91E63",
      verb: "#FFFFFF",
      adjective: "#F15060",
      adverb: "#00A95C",
      preposition: "#9B59B6",
      conjunction: "#00A95C",
      article: "#D5E0E6",
      interjection: "#FF6C2F",
      url: "#B8E6FF",
      number: "#FFD700",
      hashtag: "#B8E6FF",
    },
    accent: "#FFE800",
    cursor: "#FFE800",
    strikethrough: "#FFFFFF",
    selection: "rgba(255,232,0,0.3)",
  },
  {
    id: "midnight",
    name: "Midnight",
    text: "#e8e8e8",
    background: "#1a1a2e",
    highlight: {
      noun: "#00d9ff",
      pronoun: "#bd93f9",
      verb: "#ff79c6",
      adjective: "#50fa7b",
      adverb: "#ffb86c",
      preposition: "#8be9fd",
      conjunction: "#ffb86c",
      article: "#8A93B4",
      interjection: "#ff5555",
      url: "#69C4FF",
      number: "#F1FA8C",
      hashtag: "#69C4FF",
    },
    accent: "#00d9ff",
    cursor: "#00d9ff",
    strikethrough: "#ff79c6",
    selection: "rgba(0,217,255,0.2)",
  },
  {
    id: "sepia",
    name: "Sepia",
    text: "#5c4b37",
    background: "#f4ecd8",
    highlight: {
      noun: "#8b6914",
      pronoun: "#8e44ad",
      verb: "#a65d3f",
      adjective: "#6b8e23",
      adverb: "#d35400",
      preposition: "#16a085",
      conjunction: "#996633",
      article: "#6B7580",
      interjection: "#c0392b",
      url: "#2471A3",
      number: "#7D6608",
      hashtag: "#2471A3",
    },
    accent: "#8b6914",
    cursor: "#8b6914",
    strikethrough: "#a65d3f",
    selection: "rgba(139,105,20,0.2)",
  },
  // NEW THEMES
  {
    id: "paper",
    name: "Paper",
    text: "#1A1A1A",
    background: "#FFFFFF",
    highlight: {
      noun: "#2563EB",
      pronoun: "#7C3AED",
      verb: "#DC2626",
      adjective: "#059669",
      adverb: "#D97706",
      preposition: "#0891B2",
      conjunction: "#EA580C",
      article: "#6B7280",
      interjection: "#DB2777",
      url: "#1D4ED8",
      number: "#92400E",
      hashtag: "#1D4ED8",
    },
    accent: "#2563EB",
    cursor: "#2563EB",
    strikethrough: "#DC2626",
    selection: "rgba(37,99,235,0.2)",
  },
  {
    id: "terminal",
    name: "Terminal",
    text: "#00FF00",
    background: "#0C0C0C",
    highlight: {
      noun: "#00FF00",
      pronoun: "#00FFFF",
      verb: "#FF6600",
      adjective: "#FFFF00",
      adverb: "#FF00FF",
      preposition: "#00CCFF",
      conjunction: "#66FF66",
      article: "#669966",
      interjection: "#FF3333",
      url: "#3399FF",
      number: "#CCCC00",
      hashtag: "#3399FF",
    },
    accent: "#00FF00",
    cursor: "#00FF00",
    strikethrough: "#FF6600",
    selection: "rgba(0,255,0,0.2)",
  },
  {
    id: "warmth",
    name: "Warmth",
    text: "#4A3728",
    background: "#FFF8F0",
    highlight: {
      noun: "#B45309",
      pronoun: "#9333EA",
      verb: "#DC2626",
      adjective: "#15803D",
      adverb: "#D97706",
      preposition: "#0D9488",
      conjunction: "#EA580C",
      article: "#78716C",
      interjection: "#BE185D",
      url: "#1E40AF",
      number: "#854D0E",
      hashtag: "#1E40AF",
    },
    accent: "#D97706",
    cursor: "#D97706",
    strikethrough: "#DC2626",
    selection: "rgba(217,119,6,0.2)",
  },
  {
    id: "ocean",
    name: "Ocean",
    text: "#E2E8F0",
    background: "#0F172A",
    highlight: {
      noun: "#38BDF8",
      pronoun: "#C084FC",
      verb: "#F472B6",
      adjective: "#4ADE80",
      adverb: "#FBBF24",
      preposition: "#22D3EE",
      conjunction: "#2DD4BF",
      article: "#94A3B8",
      interjection: "#FB7185",
      url: "#60A5FA",
      number: "#FCD34D",
      hashtag: "#60A5FA",
    },
    accent: "#38BDF8",
    cursor: "#38BDF8",
    strikethrough: "#F472B6",
    selection: "rgba(56,189,248,0.2)",
  },
  {
    id: "forest",
    name: "Forest",
    text: "#D4E5D4",
    background: "#1A2F1A",
    highlight: {
      noun: "#4ADE80",
      pronoun: "#C4B5FD",
      verb: "#FCA5A5",
      adjective: "#FDE047",
      adverb: "#FDBA74",
      preposition: "#67E8F9",
      conjunction: "#86EFAC",
      article: "#9CA38A",
      interjection: "#F9A8D4",
      url: "#93C5FD",
      number: "#FDE68A",
      hashtag: "#93C5FD",
    },
    accent: "#4ADE80",
    cursor: "#4ADE80",
    strikethrough: "#FCA5A5",
    selection: "rgba(74,222,128,0.2)",
  },
  // FLEXOKI THEMES - Accessible IDE-quality color schemes
  {
    id: "flexoki-light",
    name: "Flexoki Light",
    text: "#100F0F",
    background: "#FFFCF0",
    highlight: {
      noun: "#205EA6",
      pronoun: "#5E409D",
      verb: "#AF3029",
      adjective: "#66800B",
      adverb: "#BC5215",
      preposition: "#24837B",
      conjunction: "#AD8301",
      article: "#6F6E69",
      interjection: "#A02F6F",
      url: "#2C5494",
      number: "#8B7200",
      hashtag: "#2C5494",
    },
    accent: "#205EA6",
    cursor: "#100F0F",
    strikethrough: "#AF3029",
    selection: "rgba(32,94,166,0.2)",
  },
  {
    id: "flexoki-dark",
    name: "Flexoki Dark",
    text: "#FFFCF0",
    background: "#100F0F",
    highlight: {
      noun: "#4385BE",
      pronoun: "#8B7EC8",
      verb: "#D14D41",
      adjective: "#879A39",
      adverb: "#DA702C",
      preposition: "#3AA99F",
      conjunction: "#D0A215",
      article: "#878580",
      interjection: "#CE5D97",
      url: "#5B9BD5",
      number: "#E0B429",
      hashtag: "#5B9BD5",
    },
    accent: "#4385BE",
    cursor: "#FFFCF0",
    strikethrough: "#D14D41",
    selection: "rgba(67,133,190,0.3)",
  },
  // MUSIC PLATFORM THEMES
  {
    id: "apple-music",
    name: "Apple Music",
    text: "#1D1D1F",
    background: "#FFFFFF",
    highlight: {
      noun: "#007AFF",
      pronoun: "#5856D6",
      verb: "#FF3B30",
      adjective: "#34C759",
      adverb: "#FF9500",
      preposition: "#5AC8FA",
      conjunction: "#AF52DE",
      article: "#8E8E93",
      interjection: "#FF2D55",
      url: "#007AFF",
      number: "#A2845E",
      hashtag: "#30B0C7",
    },
    accent: "#FC3C44",
    cursor: "#FC3C44",
    strikethrough: "#86868B",
    selection: "rgba(252, 60, 68, 0.15)",
  },
  {
    id: "spotify",
    name: "Spotify",
    text: "#FFFFFF",
    background: "#121212",
    highlight: {
      noun: "#1DB954",
      pronoun: "#B49BC8",
      verb: "#F573A0",
      adjective: "#1ED760",
      adverb: "#FFA42B",
      preposition: "#509BF5",
      conjunction: "#E8115B",
      article: "#B3B3B3",
      interjection: "#F59B23",
      url: "#1DB954",
      number: "#CBA6F7",
      hashtag: "#509BF5",
    },
    accent: "#1DB954",
    cursor: "#1DB954",
    strikethrough: "#535353",
    selection: "rgba(29, 185, 84, 0.25)",
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    text: "#333333",
    background: "#FFFFFF",
    highlight: {
      noun: "#FF5500",
      pronoun: "#8C6BB1",
      verb: "#E2442F",
      adjective: "#F77F00",
      adverb: "#FCBF49",
      preposition: "#FF7700",
      conjunction: "#D62828",
      article: "#999999",
      interjection: "#E36414",
      url: "#FF5500",
      number: "#9B6A2F",
      hashtag: "#FF7700",
    },
    accent: "#FF5500",
    cursor: "#FF5500",
    strikethrough: "#999999",
    selection: "rgba(255, 85, 0, 0.12)",
  },
  {
    id: "deezer",
    name: "Deezer",
    text: "#F5F5F5",
    background: "#121216",
    highlight: {
      noun: "#A238FF",
      pronoun: "#E04FD0",
      verb: "#FF4F7B",
      adjective: "#00E5FF",
      adverb: "#FFB300",
      preposition: "#7C4DFF",
      conjunction: "#536DFE",
      article: "#888888",
      interjection: "#FF6E40",
      url: "#A238FF",
      number: "#FFAB40",
      hashtag: "#7C4DFF",
    },
    accent: "#A238FF",
    cursor: "#A238FF",
    strikethrough: "#555555",
    selection: "rgba(162, 56, 255, 0.25)",
  },
  // NERV theme
  {
    id: "nerv",
    name: "NERV",
    text: "#E8E6E3",
    background: "#0A0A12",
    highlight: {
      noun: "#00D4FF",
      pronoun: "#8B5CF6",
      verb: "#FF0040",
      adjective: "#00FF41",
      adverb: "#FF6600",
      preposition: "#FFCC00",
      conjunction: "#00D4FF",
      article: "rgba(232,230,227,0.4)",
      interjection: "#FF0040",
      url: "#00D4FF",
      number: "#FFCC00",
      hashtag: "#8B5CF6",
    },
    accent: "#FF0040",
    cursor: "#FF0040",
    strikethrough: "#FF0040",
    selection: "rgba(255,0,64,0.3)",
  },
];

export const MOCK_ANALYSIS_DELAY = 1500; // ms

// Song Mode: 8 rhyme highlight colors — OKLCH-uniform ocean palette (base hue 210°, L=0.55, C=0.14)
export const RHYME_COLORS = [
  "#00859e", // teal      (H≈210)
  "#3072c1", // blue      (H≈255)
  "#7f5bb6", // purple    (H≈300)
  "#a84b84", // magenta   (H≈345)
  "#b54c3d", // red       (H≈30)
  "#a06200", // amber     (H≈75)
  "#687c00", // olive     (H≈120)
  "#008a5d", // green     (H≈165)
] as const;

export const FRESH_LOAD_TEXT = `\u201CIt is the time you have wasted for your rose that makes your rose so important.\u201D

\u201CPeople have forgotten this truth,\u201D the fox said. \u201CBut you must not forget it. You become responsible forever for what you have tamed. You are responsible for your rose.\u201D

\u201CWhat is essential is invisible to the eye,\u201D the little prince repeated, so that he would be sure to remember. \u201CIt is the time you have wasted for your rose that makes your rose so important.\u201D

The little prince went away, to look again at the roses. \u201CYou are not at all like my rose,\u201D he said. \u201CAs yet you are nothing. No one has tamed you, and you have tamed no one. You are like my fox when I first knew him. He was only a fox like a hundred thousand other foxes. But I have made him my friend, and now he is unique in all the world.\u201D

\u2014 Antoine de Saint-Exup\u00E9ry, The Little Prince`;
